/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FechamentoCaixa.java
 *
 * Created on 14/07/2012, 16:28:41
 */
package tesouraria;

import java.awt.FileDialog;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.ConectaBanco;
import utilitarios.InOut;
import utilitarios.PrintUIWindow;
import sistemaintegrado.*;

/**
 *
 * @author Notebook
 */
public class FechamentoCaixa extends javax.swing.JFrame {

    FileDialog fbSalvar;
    ConectaBanco con;
    ResultSet lRes=null;
     public String usuario = Parametros.getsNmUsuas();
    
    
    
    public FechamentoCaixa() {
        super(" FECHAMENTO DO MES ");
        initComponents();
         this.setLocationRelativeTo(null);
        fbSalvar = new FileDialog(this, "Salvar Arquivo", FileDialog.SAVE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ano = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EntradaMes = new javax.swing.JTextField();
        SaidaMes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Pesquisa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        SaldoMes = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        SaldoFim = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Saida = new javax.swing.JTextField();
        Entrada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Imprimir = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        SalvaArquivo = new javax.swing.JButton();
        Progresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("FECHAMENTO DO MES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MES DE MOVIMENTO :");

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANEIRO", "FEVEREIRO", "MARCO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO", " " }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ANO DE MOVIMENTO :");

        ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("DEMONSTRATIVO RESUMIDO DO MES");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("TOTAL DE ENTRADAS DO MES :");

        EntradaMes.setEditable(false);
        EntradaMes.setForeground(new java.awt.Color(0, 0, 204));

        SaidaMes.setEditable(false);
        SaidaMes.setForeground(new java.awt.Color(204, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("TOTAL DE SAÍDAS  DO MES :");

        Pesquisa.setText("Fechar Caixa");
        Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PesquisaMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("SALDO : ");

        SaldoMes.setEditable(false);
        SaldoMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("DEMONSTRATIVO GERAL");

        SaldoFim.setEditable(false);
        SaldoFim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("SALDO : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("TOTAL DE SAÍDAS  :");

        Saida.setEditable(false);
        Saida.setForeground(new java.awt.Color(204, 0, 0));

        Entrada.setEditable(false);
        Entrada.setForeground(new java.awt.Color(0, 0, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("TOTAL DE ENTRADAS  : ");

        Imprimir.setText("Imprimir");
        Imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImprimirMousePressed(evt);
            }
        });

        Fechar.setText("Fechar");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FecharMousePressed(evt);
            }
        });

        SalvaArquivo.setText("Salvar");
        SalvaArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalvaArquivoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(40, 40, 40)
                                    .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(204, 204, 204)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(SaldoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EntradaMes)
                                            .addComponent(SaidaMes)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SaldoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SalvaArquivo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                                    .addGap(70, 70, 70)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3))
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4))
                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Pesquisa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EntradaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaidaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SaldoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaldoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Imprimir)
                        .addComponent(Fechar)
                        .addComponent(SalvaArquivo))
                    .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ImprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirMousePressed
    SalvaArquivo.setVisible(false);
    Pesquisa.setVisible(false);
    Fechar.setVisible(false);
    
    Imprimir.addActionListener(new PrintUIWindow(this));
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    InOut.MsgDeAviso("IMPRESSÃO", "IMPRESSÃO SENDO REALIZADA");
    Pesquisa.setVisible(true);
    Fechar.setVisible(true);
    SalvaArquivo.setVisible(true);
    
    
    
}//GEN-LAST:event_ImprimirMousePressed

private void PesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisaMousePressed
// TODO add your handling code here:
    CaixaMes();
    CaixaGeral();
   
}//GEN-LAST:event_PesquisaMousePressed

private void FecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMousePressed
    
    this.dispose();
   
}//GEN-LAST:event_FecharMousePressed

    private void SalvaArquivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvaArquivoMousePressed
  int confirma = 0;  
  confirma = JOptionPane.showConfirmDialog(null,"Deseja salvar arquivo Simplificado ?","Salvar",JOptionPane.YES_NO_CANCEL_OPTION);
    System.out.println(confirma);
    if (confirma == 0){
        SalvaArquivoCSV();
    }else if(confirma == 1){
        SalvaArquivoDetalhadoCSV();
    }
        
        
       
    }//GEN-LAST:event_SalvaArquivoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FechamentoCaixa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada;
    private javax.swing.JTextField EntradaMes;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton Pesquisa;
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JTextField Saida;
    private javax.swing.JTextField SaidaMes;
    private javax.swing.JTextField SaldoFim;
    private javax.swing.JTextField SaldoMes;
    private javax.swing.JButton SalvaArquivo;
    private javax.swing.JComboBox ano;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox mes;
    // End of variables declaration//GEN-END:variables

    public void CaixaMes()  {
         con=new ConectaBanco();
        String sSql=new String();
        String verifica = new String();
        double entradames=0.0d;
        double saidames=0.0d;
        double saldofinalmes=0.0d;
        double calcula=0.0d;
        double calcula2=0.0d;
        
        entradames=0;
        saidames=0;
        saldofinalmes=0;
        calcula=0;
        calcula2=0;
        
        sSql="SELECT DATA_MES,DATA_ANO,VALOR_SAIDA,VALOR_ENTRADA FROM FINANCEIRO WHERE DATA_MES='"+mes.getSelectedItem()+"' AND DATA_ANO='"+ano.getSelectedItem()+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro(null,"Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
        
        lRes=con.resultset;        
        System.out.println(lRes);
        System.out.println(sSql);
        try 
        {           
            while (lRes.next())
            {
                                               lRes.getString("data_mes");
                                               lRes.getString("data_ano");
                 saidames = Double.parseDouble(lRes.getString("valor_saida").replace(',', '.'));
                 entradames = Double.parseDouble(lRes.getString("valor_entrada").replace(',', '.'));
                 calcula = calcula + entradames;
                 calcula2 = calcula2 + saidames;   
                 saldofinalmes=saldofinalmes + entradames - saidames;  
                                               
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();
       /* 
       SaldoMes.setText(String.valueOf(saldofinalmes).replace(',', '.'));
       SaidaMes.setText(String.valueOf(calcula2).replace(',', '.'));
       EntradaMes.setText(String.valueOf(calcula).replace(',', '.'));
       */
        DecimalFormat  df = new DecimalFormat();
        df.applyPattern("R$ #,##0.00");
       SaldoMes.setText(df.format(saldofinalmes));
       SaidaMes.setText(df.format(calcula2));
       EntradaMes.setText(df.format(calcula));
       
    }

    public void CaixaGeral() {
       con=new ConectaBanco();
        String sSql=new String();
        double entrada=0.0d;
        double saida=0.0d;
        double saldofinal=0.0d;
        double calcula=0.0d;
        double calcula2=0.0d;
        entrada=0;
        saida=0;
        saldofinal=0;
        calcula=0;
        calcula2=0;
        
        sSql="SELECT DATA_MES,DATA_ANO,VALOR_SAIDA,VALOR_ENTRADA FROM FINANCEIRO ;";//WHERE DATA_MES='"+mes.getSelectedItem()+"' AND DATA_ANO='"+ano.getSelectedItem()+"';";

        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro(null,"Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
        
        lRes=con.resultset;        
        System.out.println(lRes);
        System.out.println(sSql);
        try 
        {           
            while (lRes.next())
            {
                                               lRes.getString("data_mes");
                                               lRes.getString("data_ano");
                 saida = Double.parseDouble(lRes.getString("valor_saida").replace(',', '.'));
                 entrada = Double.parseDouble(lRes.getString("valor_entrada").replace(',', '.'));
                 calcula = calcula + entrada;
                 calcula2 = calcula2 + saida;   
                 saldofinal=saldofinal + entrada - saida;  
                                               
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();
      DecimalFormat  df = new DecimalFormat();
        df.applyPattern("R$ #,##0.00");
       SaldoFim.setText(df.format(saldofinal));
       Saida.setText(df.format(calcula2));
       Entrada.setText(df.format(calcula));
       
       
       
       
       
 
    }

    private void SalvaArquivoCSV() {
        String nome_do_arquivo;
        fbSalvar.setVisible(true);
        if (fbSalvar.getFile()==null) return;
        nome_do_arquivo = fbSalvar.getDirectory()+fbSalvar.getFile();
        PrintWriter out = null;
        try {
            out = new PrintWriter(nome_do_arquivo+".csv");// **** FORMA MAIS RAPIDO DE SALVAR UM ARQUIVO EM .CSV*****
            
            out.println("*******RELATORIO FINANCEIRO - FECHAMENTO DO MES "+mes.getSelectedItem()+" ANO "+ano.getSelectedItem()+"*******;");
            out.println("MES;ANO;TOTAL DE ENTRADAS;TOTAL DE SAIDAS;SALDO DO MES");
            out.println(mes.getSelectedItem()+";"+ano.getSelectedItem()+";"+EntradaMes.getText()+";"
                        +SaidaMes.getText()+";"+SaldoMes.getText()+";");
            out.println(";");
            
            out.println("******DEMONSTRATIVO TOTAL ( RESUMIDO )******");
            out.println("TOTAL DE ENTRADAS;TOTAL DE SAIDAS;SALDO FINAL;");
            out.println(Entrada.getText()+";"+Saida.getText()+";"+SaldoFim.getText()+";");
            out.println(";");
            
            out.println("USUARIO DO SISTEMA;"+usuario+";");
            out.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }

    private void SalvaArquivoDetalhadoCSV() {
          String nome_do_arquivo,sSql,contador;
          int i=0;
          int recebeProgresso=0;
          String RelDia,RelMes,RelAno,RelEntrada,RelSaida,RelDescricao;
        fbSalvar.setVisible(true);
        if (fbSalvar.getFile()==null) return;
        nome_do_arquivo = fbSalvar.getDirectory()+fbSalvar.getFile();
        PrintWriter out = null;
        try {       
            out = new PrintWriter(nome_do_arquivo+".csv");// **** FORMA MAIS RAPIDO DE SALVAR UM ARQUIVO EM .CSV*****
            out.println("*******RELATORIO FINANCEIRO - FECHAMENTO DO MES"+mes.getSelectedItem()+" ANO "+ano.getSelectedItem()+"*******;");
            out.println("DIA;MES;ANO;ENTRADAS;SAIDAS;DESCRICAO");
            sSql="SELECT * FROM FINANCEIRO WHERE DATA_MES='"+mes.getSelectedItem()+"' AND DATA_ANO='"+ano.getSelectedItem()+"';";
            contador="SELECT data_mes,data_ano,Count(*) as contador FROM FINANCEIRO WHERE DATA_MES='"+mes.getSelectedItem()+"' AND DATA_ANO='"+ano.getSelectedItem()+"';";
        con.conecta();
        con.executaSelect(contador); 
        //System.out.println("aqui é o contador"+contador);
        lRes=con.resultset;        
      // System.out.println(lRes);
       //System.out.println(contador);
        try {
            while (lRes.next()){
                   recebeProgresso=Integer.parseInt( lRes.getString("contador"));
            }
            } catch (SQLException ex) {
            InOut.MsgDeErro(null, contador);
        }
         // System.out.println(lRes);
        System.out.println("***********"+recebeProgresso);
        Progresso.setMaximum(recebeProgresso);
        Progresso.setMinimum(0); 
    
         
         if(!con.conecta())
        {
            InOut.MsgDeErro(null,"Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
        
        lRes=con.resultset;        
        System.out.println(lRes);
        System.out.println(sSql);
        try 
        {           
            while (lRes.next())
            {
                 RelDia=lRes.getString("data_dia");
                 RelMes=lRes.getString("data_mes");
                 RelAno=lRes.getString("data_ano");
                 RelEntrada=lRes.getString("valor_entrada");
                 RelSaida=lRes.getString("valor_saida");
                 RelDescricao=lRes.getString("descricao");
                 
                 if("0".equals(RelEntrada)){
                    out.println(RelDia+";"+RelMes+";"+RelAno+"; ;"+RelSaida+";"+RelDescricao+";"); 
                 }else if("0".equals(RelSaida)){
                     out.println(RelDia+";"+RelMes+";"+RelAno+";"+RelEntrada+"; ;"+RelDescricao+";");
                 }
     
                 try {
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                    }
                    i++;
                    Progresso.setValue(i); 
                 
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FechamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        out.println("*******RELATORIO FINANCEIRO - FECHAMENTO DO MES"+mes.getSelectedItem()+" ANO "+ano.getSelectedItem()+"*******;");
            out.println("DIA;MES;ANO;ENTRADAS;SAIDAS;DESCRICAO");
            out.println("  ;  ;  ;TOTAL DE ENTRADAS;TOTAL DE SAIDAS;SALDO DO MES");
            out.println("  ;  ;  ;"+EntradaMes.getText()+";"
                        +SaidaMes.getText()+";"+SaldoMes.getText()+";");
            out.println(";");
            
            out.println("******DEMONSTRATIVO TOTAL ( RESUMIDO )******");
            out.println("TOTAL DE ENTRADAS;TOTAL DE SAIDAS;SALDO FINAL;");
            out.println(Entrada.getText()+";"+Saida.getText()+";"+SaldoFim.getText()+";");
            out.println(";");
            
            out.println("USUARIO DO SISTEMA;"+usuario+";");
            out.close();    
    InOut.MsgDeInformacao(null, "Arquivo Salvo!");
    }
}
